### ISSUE TITLE
node okapi.py should contain source code

### ISSUE THREAD

**Issue by int-e** [catseye/Chrysoberyl#7]
The link from the Okapi node to the okapi.py node suggests that the latter node is supposed to contain source code for an Okapi interpreter, but instead there's just a list of dependencies.

**Comment by cpressey** [comment]
The structure of Chrysoberyl has changed significantly since this was written, but the following may still be relevant: In Chrysoberyl, there may be entries with names that look like filenames, but which do not contain the contents of that file.  They just name a file that exists elsewhere in the world.  A current example is: http://catseye.tc/article/Language_Implementations#thuerb .

These are no longer accessed by a URL which ends in the name that looks like a filename, so the confusion between the entry `thue.rb` and the `thue.rb` file itself should be lessened now.

For Okapi specifically, no link to the `okapi.py` file itself was given in the `okapi.py` node, because the `okapi.py` file is not public.  Chrysoberyl previously contained entries for closed-source projects such as Okapi and ETHEL.  It no longer contains entries for such projects.
